name = "hyperlocal-worker"
main = "src/index.js"
compatibility_date = "2026-04-02"

[[durable_objects.bindings]]
name = "CHAT_ROOM_DO"
class_name = "ChatRoomDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoomDO"]

[vars]
BACKEND_URL = "http://localhost:3001"
DEV_EXPOSE_OTP = "true"
